In [1]:
import numpy as np
import pandas as pd
#import library numpy dan pandas

In [2]:
df=pd.read_csv('tweets_csv_siap.csv',sep=';')
#read csv file

In [3]:
df.head()
#verifikasi 5 row data pertama

tweet  \
0  el_atheos ridwankamil ya mungkin karena peremp...   
1  ridwankamil dbmpkotabdg kang teman saya tertim...   
2  di tribun jabar biasanya suka di post agenda k...   
3  dbmpkotabdg rt fajriattack: lapor pak ridwanka...   
4  diskamtam bapak/ibu mau tanya kalo pemeliharaa...   

                       kelas  
0  bukan keluhan atau respon  
1                    keluhan  
2  bukan keluhan atau respon  
3                    keluhan  
4  bukan keluhan atau respon

In [4]:
df.tail()
#verifikasi 5 row data terakhir

tweet  \
7522  rt yayan_98: ridwankamil pa tong nyalon ka jak...   
7523  whatt??di jabar msh byk daerah potensi yg blm ...   
7524  dbmpkotabdg kelrancabolang ridwankamil pemumbd...   
7525  buka twitter muncul promote ginian. gimana atu...   
7526  rt yogipamadya: kang ridwankamil angkot jadi t...   

                          kelas  
7522  bukan keluhan atau respon  
7523  bukan keluhan atau respon  
7524                    keluhan  
7525                    keluhan  
7526  bukan keluhan atau respon

In [5]:
df.columns
#verifikasi nama kolom

Index(['tweet', 'kelas'], dtype='object')

In [6]:
df.isnull().sum()
#verifikasi kelengkapan data

tweet    0
kelas    0
dtype: int64

In [7]:
len(df)
#verdifikasi panjang row data

7527

In [8]:
df['kelas'].value_counts()
#melihat unik value dari kolom label nya

bukan keluhan atau respon    3865
keluhan                      2745
respon                        917
Name: kelas, dtype: int64

In [9]:
import sklearn

In [10]:
from sklearn.model_selection import train_test_split
#library untuk split data test dan data training

In [11]:
X = df['tweet']

In [12]:
y = df['kelas']
#label 'keluhan', 'respon' atau 'bukan keluhan atau respon'

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state=42)
#dipakai 30% untuk test size, 70% nya training size

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
from sklearn.naive_bayes import MultinomialNB
#dipakai algoritma naive bayes

In [16]:
from sklearn.pipeline import Pipeline
#Pipeline kelas perform kombinasi vectorizer dan tfidf dalam satu syntax

In [17]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',MultinomialNB())])
#semua step dalam satu single step

In [18]:
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [19]:
predictions = text_clf.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix,classification_report

In [21]:
print(confusion_matrix(y_test,predictions))

[[1042  111   18]
 [ 154  662    0]
 [  33    4  235]]


In [22]:
print(classification_report(y_test,predictions))
#statistik hasil test dari training

                           precision    recall  f1-score   support

bukan keluhan atau respon       0.85      0.89      0.87      1171
                  keluhan       0.85      0.81      0.83       816
                   respon       0.93      0.86      0.90       272

                micro avg       0.86      0.86      0.86      2259
                macro avg       0.88      0.86      0.86      2259
             weighted avg       0.86      0.86      0.86      2259



In [23]:
from sklearn import metrics

In [24]:
metrics.accuracy_score(y_test,predictions)
#tingkat akurasi nya

0.8583444001770695

In [25]:
text_clf.predict(["Buka twitter muncul promote ginian. Gimana atuh kalo anak kecil yg liat? Cc: @Menkominfo @ridwankamil https://t.co/3okfeZIsap"])
#masukkan tweet uji di sini - belum pakai GUI

array(['keluhan'], dtype='<U25')