In [1]:
import numpy as np

In [2]:
import pandas as pd
#import library numpy dan pandas

In [3]:
df=pd.read_csv('tweets_csv_siap.csv',sep=';')
#read csv file

In [4]:
df.head()
#verifikasi 5 row data pertama

tweet  \
0  el_atheos ridwankamil ya mungkin karena peremp...   
1  ridwankamil dbmpkotabdg kang teman saya tertim...   
2  di tribun jabar biasanya suka di post agenda k...   
3  dbmpkotabdg rt fajriattack: lapor pak ridwanka...   
4  diskamtam bapak/ibu mau tanya kalo pemeliharaa...   

                       kelas  
0  bukan keluhan atau respon  
1                    keluhan  
2  bukan keluhan atau respon  
3                    keluhan  
4  bukan keluhan atau respon

In [5]:
df.tail()
#verifikasi 5 row data terakhir

tweet  \
7522  rt yayan_98: ridwankamil pa tong nyalon ka jak...   
7523  whatt??di jabar msh byk daerah potensi yg blm ...   
7524  dbmpkotabdg kelrancabolang ridwankamil pemumbd...   
7525  buka twitter muncul promote ginian. gimana atu...   
7526  rt yogipamadya: kang ridwankamil angkot jadi t...   

                          kelas  
7522  bukan keluhan atau respon  
7523  bukan keluhan atau respon  
7524                    keluhan  
7525                    keluhan  
7526  bukan keluhan atau respon

In [6]:
df.columns
#verifikasi nama kolom

Index(['tweet', 'kelas'], dtype='object')

In [7]:
df.isnull().sum()
#verifikasi kelengkapan data

tweet    0
kelas    0
dtype: int64

In [8]:
len(df)
#verdifikasi panjang row data

7527

In [9]:
df['tweet']
#verifikasi isi tweet

0       el_atheos ridwankamil ya mungkin karena peremp...
1       ridwankamil dbmpkotabdg kang teman saya tertim...
2       di tribun jabar biasanya suka di post agenda k...
3       dbmpkotabdg rt fajriattack: lapor pak ridwanka...
4       diskamtam bapak/ibu mau tanya kalo pemeliharaa...
5       pa ridwankamil tempat kerja saya tgl 25 tetep ...
6       pdamtirtaweningridwankamil  00106700466 punten...
7       rt kendiadiputra: anak sma yang ketahuan mencu...
8       pdamtirtawening ternyata sudah ada warga yg ko...
9       kang ridwankamil jalan di muararajeun baru bar...
10      rt adammaulud: didinyamah kieu 👍 bosss! kumaha...
11      pak ridwankamil punten tolong marahin motor yg...
12      dbmpkotabdg ridwankamil hatur nuhun dbmp lampu...
13      kalo pemkotbandung ridwankamil mau batasi kend...
14      rt iqbalfg: pak ridwankamil punten tolong mara...
15      pak tadi saya habis dari kebun binatang itu ke...
16      rt tadjiuinbdg: ridwankamil lapor pak mobil ni...
17      bonbin

In [10]:
df['kelas']
#verifikasi isi kolom kelas

0       bukan keluhan atau respon
1                         keluhan
2       bukan keluhan atau respon
3                         keluhan
4       bukan keluhan atau respon
5                         keluhan
6                         keluhan
7                         keluhan
8       bukan keluhan atau respon
9                         keluhan
10                        keluhan
11                        keluhan
12      bukan keluhan atau respon
13      bukan keluhan atau respon
14                        keluhan
15                        keluhan
16                        keluhan
17                        keluhan
18      bukan keluhan atau respon
19                        keluhan
20      bukan keluhan atau respon
21                        keluhan
22                        keluhan
23                        keluhan
24      bukan keluhan atau respon
25                        keluhan
26      bukan keluhan atau respon
27      bukan keluhan atau respon
28      bukan keluhan atau respon
29      bukan 

In [11]:
df['kelas'].value_counts()
#melihat unik value dari kolom label nya

bukan keluhan atau respon    3865
keluhan                      2745
respon                        917
Name: kelas, dtype: int64

In [12]:
import sklearn

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = df['tweet']

In [15]:
y = df['kelas']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state=42)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
count_vect = CountVectorizer()

In [19]:
X_train_counts = count_vect.fit_transform(X_train)

In [20]:
X_train_counts

<5268x10578 sparse matrix of type '<class 'numpy.int64'>'
	with 90830 stored elements in Compressed Sparse Row format>

In [21]:
X_train.shape

(5268,)

In [22]:
X_train_counts.shape

(5268, 10578)

In [23]:
from sklearn.feature_extraction.text import TfidfTransformer

In [24]:
tfidf_transformer = TfidfTransformer()

In [25]:
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [26]:
X_train_tfidf.shape
#bukan lagi hanya counts tapi tfidf

(5268, 10578)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
vectorizer = TfidfVectorizer()

In [29]:
X_tain_tfidf=vectorizer.fit_transform(X_train)
#Menggabungkan proses vectorizer dan tfidf

In [30]:
from sklearn.svm import LinearSVC

In [31]:
clf = LinearSVC()

In [32]:
clf.fit(X_train_tfidf,y_train)
#model yang digunakan

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [33]:
from sklearn.pipeline import Pipeline
#Pipeline kelas perform kombinasi semua nya

In [34]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
#semua step dalam satu single step

In [35]:
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [36]:
predictions = text_clf.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
print(confusion_matrix(y_test,predictions))

[[1045  117    9]
 [  99  716    1]
 [   2    4  266]]


In [39]:
print(classification_report(y_test,predictions))

                           precision    recall  f1-score   support

bukan keluhan atau respon       0.91      0.89      0.90      1171
                  keluhan       0.86      0.88      0.87       816
                   respon       0.96      0.98      0.97       272

                micro avg       0.90      0.90      0.90      2259
                macro avg       0.91      0.92      0.91      2259
             weighted avg       0.90      0.90      0.90      2259



In [40]:
from sklearn import metrics

In [41]:
metrics.accuracy_score(y_test,predictions)

0.8972996901283754

In [43]:
text_clf.predict(["paste uji tweets disini"])

array(['bukan keluhan atau respon'], dtype=object)