In [1]:
import numpy as np

In [2]:
import pandas as pd
#import library numpy dan pandas

In [3]:
df=pd.read_csv('tweets_csv_siap.csv',sep=';')
#read csv file

In [4]:
df.head()
#verifikasi 5 row data pertama saja

tweet  \
0  el_atheos ridwankamil ya mungkin karena peremp...   
1  ridwankamil dbmpkotabdg kang teman saya tertim...   
2  di tribun jabar biasanya suka di post agenda k...   
3  dbmpkotabdg rt fajriattack: lapor pak ridwanka...   
4  diskamtam bapak/ibu mau tanya kalo pemeliharaa...   

                       kelas  
0  bukan keluhan atau respon  
1                    keluhan  
2  bukan keluhan atau respon  
3                    keluhan  
4  bukan keluhan atau respon

In [5]:
df.tail()
#verifikasi 5 row data terakhir saja

tweet  \
7522  rt yayan_98: ridwankamil pa tong nyalon ka jak...   
7523  whatt??di jabar msh byk daerah potensi yg blm ...   
7524  dbmpkotabdg kelrancabolang ridwankamil pemumbd...   
7525  buka twitter muncul promote ginian. gimana atu...   
7526  rt yogipamadya: kang ridwankamil angkot jadi t...   

                          kelas  
7522  bukan keluhan atau respon  
7523  bukan keluhan atau respon  
7524                    keluhan  
7525                    keluhan  
7526  bukan keluhan atau respon

In [6]:
df.columns
#verifikasi nama kolom

Index(['tweet', 'kelas'], dtype='object')

In [7]:
df.isnull().sum()
#verifikasi kelengkapan data

tweet    0
kelas    0
dtype: int64

In [8]:
len(df)
#verdifikasi panjang row data

7527

In [9]:
df['kelas'].value_counts()
#melihat unik value dari kolom label nya

bukan keluhan atau respon    3865
keluhan                      2745
respon                        917
Name: kelas, dtype: int64

In [10]:
import sklearn

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df['tweet']
#isi tweets

In [13]:
y = df['kelas']
#label 'keluhan', 'respon' dan 'bukan keluhan atau respon'

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state=42)
#test data 30%, traing data 70%

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
from sklearn.svm import LinearSVC
#Menggunakan algoritma SVM

In [17]:
from sklearn.pipeline import Pipeline
#Pipeline kelas perform kombinasi semua nya tfidf vectorizer dan model yg dipakai

In [18]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
#semua step dalam satu single step

In [19]:
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [20]:
predictions = text_clf.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(confusion_matrix(y_test,predictions))

[[1045  117    9]
 [  99  716    1]
 [   2    4  266]]


In [23]:
print(classification_report(y_test,predictions))
#statistik hasil test dari training data

                           precision    recall  f1-score   support

bukan keluhan atau respon       0.91      0.89      0.90      1171
                  keluhan       0.86      0.88      0.87       816
                   respon       0.96      0.98      0.97       272

                micro avg       0.90      0.90      0.90      2259
                macro avg       0.91      0.92      0.91      2259
             weighted avg       0.90      0.90      0.90      2259



In [24]:
from sklearn import metrics

In [25]:
metrics.accuracy_score(y_test,predictions)
#akurasi untuk 30% data test

0.8972996901283754

In [26]:
text_clf.predict(["RT @infobdg: #suaraBDG via @aldlansyah: Tombol sama lampu penyebrangannya engga berfungsi nih, pak cc: @dishub_kotabdg https://t.co/NvtS3Eq…"])
#paste syntax disini untuk di uji - belum pakai GUI

array(['keluhan'], dtype=object)